# Generated by Django 3.2.16 on 2024-10-05 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLinkRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_link', models.CharField(max_length=255, unique=True, verbose_name='Короткая ссылка')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shortlink', to='api.recipe')),
            ],
        ),
    ]
