# Generated by Django 3.2.16 on 2024-10-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shortlinkrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlinkrecipe',
            name='original_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
