# Generated by Django 3.2.16 on 2024-10-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20241010_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlinkrecipe',
            name='original_link',
            field=models.URLField(verbose_name='Ссылка на рецепт'),
        ),
    ]
