# Generated by Django 3.2.16 on 2024-09-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='avatars', verbose_name='Аватар'),
        ),
    ]
