# Generated by Django 3.2.16 on 2024-09-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='users', verbose_name='Аватар'),
        ),
    ]
